// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW0y7YPXmystM-UdO2pza-aZ8_J62oLMs',
    appId: '1:993695196700:web:01478a5b3455bd02bd61d9',
    messagingSenderId: '993695196700',
    projectId: 'margavoid-f30bd',
    authDomain: 'margavoid-f30bd.firebaseapp.com',
    storageBucket: 'margavoid-f30bd.firebasestorage.app',
    measurementId: 'G-6H7P6Q9M5X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGfyFxFZIU1Bme46_Y3-pdrillPBACl8c',
    appId: '1:993695196700:android:7345d11152f15b9fbd61d9',
    messagingSenderId: '993695196700',
    projectId: 'margavoid-f30bd',
    storageBucket: 'margavoid-f30bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA7ZYqorFxAAoVuYggmuESN0nkqqaJWCs',
    appId: '1:993695196700:ios:43feeb4f8fa589afbd61d9',
    messagingSenderId: '993695196700',
    projectId: 'margavoid-f30bd',
    storageBucket: 'margavoid-f30bd.firebasestorage.app',
    iosClientId: '993695196700-ujf03i9jitmtvspc2qkt9dfsvos5ma9q.apps.googleusercontent.com',
    iosBundleId: 'com.example.nexora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAA7ZYqorFxAAoVuYggmuESN0nkqqaJWCs',
    appId: '1:993695196700:ios:43feeb4f8fa589afbd61d9',
    messagingSenderId: '993695196700',
    projectId: 'margavoid-f30bd',
    storageBucket: 'margavoid-f30bd.firebasestorage.app',
    iosClientId: '993695196700-ujf03i9jitmtvspc2qkt9dfsvos5ma9q.apps.googleusercontent.com',
    iosBundleId: 'com.example.nexora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCW0y7YPXmystM-UdO2pza-aZ8_J62oLMs',
    appId: '1:993695196700:web:0220a7fe4482d6bfbd61d9',
    messagingSenderId: '993695196700',
    projectId: 'margavoid-f30bd',
    authDomain: 'margavoid-f30bd.firebaseapp.com',
    storageBucket: 'margavoid-f30bd.firebasestorage.app',
    measurementId: 'G-XM6DG6CMR6',
  );
}
